{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pageSize", "label": "pageSize", "query": "16384" },
   { "name": "cores", "query": "8" },
   { "name": "blockSize", "query": "4096" },
   { "name": "cpu_states", "query": "user,system,idle,nice" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1 / $cores", "legendFormat": "per cpu" }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "idle"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "system"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "CPU ($cpu_states)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "repeat": "cpu_states",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"0\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"0\"}[1m]))) * 100",
     "legendFormat": "0"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"1\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"1\"}[1m]))) * 100",
     "legendFormat": "1"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"2\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"2\"}[1m]))) * 100",
     "legendFormat": "2"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"3\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"3\"}[1m]))) * 100",
     "legendFormat": "3"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"4\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"4\"}[1m]))) * 100",
     "legendFormat": "4"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"5\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"5\"}[1m]))) * 100",
     "legendFormat": "5"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"6\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"6\"}[1m]))) * 100",
     "legendFormat": "6"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"7\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"7\"}[1m]))) * 100",
     "legendFormat": "7"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "IO (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"disk0\"}[1m]) / 1024",
     "legendFormat": "read (KB)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"disk0\"}[1m]) / 1024",
     "legendFormat": "write (KB)"
    }
   ]
  },
  {
   "title": "Requests (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"disk0\"}[1m])",
     "legendFormat": "read (count)"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"disk0\"}[1m])",
     "legendFormat": "write (count)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "faults (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_swapped_in_pages_total[1m])",
     "legendFormat": "swap_ins (pages)"
    },
    {
     "expr": "rate(node_memory_cow_faults[1m])",
     "legendFormat": "cow faults"
    },
    {
     "expr": "rate(node_memory_zero_filled_pages[1m])",
     "legendFormat": "0filled faults"
    }
   ]
  },
  {
   "title": "memory pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_anonymous_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "anonymous (GB)"
    },
    {
     "expr": "(node_memory_filesystem_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "filesystem"
    },
    {
     "expr": "(node_memory_wired_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "wired (GB)"
    },
    {
     "expr": "(node_memory_free_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "free (GB)"
    },
    {
     "expr": "(node_memory_compressed_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "compressed (GB)"
    }
   ]
  },
  {
   "title": "Swap space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_swap_used_bytes/(1024*1024*1024)",
     "legendFormat": "used (GB)"
    },
    {
     "expr": "node_memory_swap_total_bytes/(1024*1024*1024)",
     "legendFormat": "total (GB)"
    }
   ]
  },
  {
   "title": "Swap out (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(node_memory_swapped_out_pages_total[1m]) * $blockSize)/(1024 * 1024 * 1024)",
     "legendFormat": "GB"
    }
   ]
  }
 ]
}