{
 "title": "My System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pageSize", "label": "pageSize", "query": "4096" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1/6", "legendFormat": "per cpu" }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "idle"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "system"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "nice"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "irq"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "softirq"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "iowait"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"steal\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"irq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"softirq\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"iowait\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "Interrupts serviced (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(node_intr_total[1m])", "legendFormat": "count" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "faults (diff)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pgmajfault[5m])",
     "legendFormat": "major"
    },
    {
     "expr": "increase(node_vmstat_pgfault[5m]) - increase(node_vmstat_pgmajfault[5m])",
     "legendFormat": "minor"
    }
   ]
  },
  {
   "title": "Swapping (diff)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pswpin[5m])",
     "legendFormat": "swap in (pages)"
    },
    {
     "expr": "increase(node_vmstat_pswpout[5m])",
     "legendFormat": "swap out (pages)"
    }
   ]
  },
  {
   "title": "Paging (diff)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pgpgout[5m])",
     "legendFormat": "paged out (pages)"
    },
    {
     "expr": "increase(node_vmstat_pgpgin[5m])",
     "legendFormat": "paged in (pages)"
    }
   ]
  },
  {
   "title": "memory pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_AnonPages_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "anonymous (GB)"
    },
    {
     "expr": "(node_memory_Active_file_bytes + node_memory_Inactive_file_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "filesystem (GB)"
    },
    {
     "expr": "(node_memory_MemAvailable_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "free (GB)"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_AnonPages_bytes - node_memory_Active_file_bytes - node_memory_Inactive_file_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "others (GB)"
    }
   ]
  },
  {
   "title": "Swap space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes/(1024*1024*1024)",
     "legendFormat": "total (GB)"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)/(1024*1024*1024)",
     "legendFormat": "used (GB)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "IO (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[1m])/1024",
     "legendFormat": "read (KB)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[1m])/1024",
     "legendFormat": "write (KB)"
    }
   ]
  },
  {
   "title": "Requests (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\"}[1m])/1024",
     "legendFormat": "read (count)"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"sda\"}[1m])/1024",
     "legendFormat": "write (count)"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "count" }
   ]
  },
  {
   "title": "Flush requests (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_flush_requests_total{device=\"sda\"}[1m])",
     "legendFormat": "count"
    }
   ]
  }
 ]
}