{
 "title": "Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "pageSize", "label": "pageSize", "query": "16384" },
   {
    "name": "cores",
    "label": "Num Cores",
    "query": {
     "query": "query_result(count(count(node_cpu_seconds_total) by (cpu)))"
    }
   },
   { "name": "blockSize", "query": "4096" },
   { "name": "cpu_states", "query": "user,system,idle,nice" },
   { "name": "network_interfaces", "query": "en0,lo0" },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1 / $cores", "legendFormat": "per cpu" }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "idle"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "system"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m]))/(sum(idelta(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"nice\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"user\"}[1m])) + sum(idelta(node_cpu_seconds_total{mode=\"idle\"}[1m])))) * 100",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "CPU ($cpu_states)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "repeat": "cpu_states",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"0\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"0\"}[1m]))) * 100",
     "legendFormat": "0"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"1\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"1\"}[1m]))) * 100",
     "legendFormat": "1"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"2\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"2\"}[1m]))) * 100",
     "legendFormat": "2"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"3\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"3\"}[1m]))) * 100",
     "legendFormat": "3"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"4\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"4\"}[1m]))) * 100",
     "legendFormat": "4"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"5\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"5\"}[1m]))) * 100",
     "legendFormat": "5"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"6\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"6\"}[1m]))) * 100",
     "legendFormat": "6"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"7\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"7\"}[1m]))) * 100",
     "legendFormat": "7"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"8\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"8\"}[1m]))) * 100",
     "legendFormat": "8"
    },
    {
     "expr": "(sum(idelta(node_cpu_seconds_total{mode=~\"$cpu_states\", cpu=\"8\"}[1m]))/sum(idelta(node_cpu_seconds_total{cpu=\"8\"}[1m]))) * 100",
     "legendFormat": "9"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "faults (per second)",
   "type": "timeseries",
   "description": "A datapoint at time t = T represents avg number of faults per second from t = T - $__rate_interval to t = T",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_memory_swapped_in_pages_total[$__rate_interval])",
     "legendFormat": "swap_ins (pages)"
    },
    {
     "expr": "rate(node_memory_cow_faults[$__rate_interval])",
     "legendFormat": "cow faults"
    },
    {
     "expr": "rate(node_memory_zero_filled_pages[$__rate_interval])",
     "legendFormat": "0filled faults"
    },
    {
     "expr": "delta(node_memory_swapped_in_pages_total[$__range])",
     "legendFormat": "swap_ins total (pages)"
    },
    {
     "expr": "delta(node_memory_cow_faults[$__range])",
     "legendFormat": "cow faults total"
    },
    {
     "expr": "delta(node_memory_zero_filled_pages[$__range])",
     "legendFormat": "0filled faults total"
    }
   ]
  },
  {
   "title": "memory pages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(node_memory_anonymous_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "anonymous (GB)"
    },
    {
     "expr": "(node_memory_filesystem_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "filesystem"
    },
    {
     "expr": "(node_memory_wired_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "wired (GB)"
    },
    {
     "expr": "(node_memory_free_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "free (GB)"
    },
    {
     "expr": "(node_memory_compressed_pages * $pageSize) / (1024 * 1024 * 1024)",
     "legendFormat": "compressed (GB)"
    }
   ]
  },
  {
   "title": "Swap space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_memory_swap_used_bytes/(1024*1024*1024)",
     "legendFormat": "used (GB)"
    },
    {
     "expr": "node_memory_swap_total_bytes/(1024*1024*1024)",
     "legendFormat": "total (GB)"
    }
   ]
  },
  {
   "title": "Swap out (per second)",
   "type": "timeseries",
   "description": "A datapoint at time t = T represents avg amount of swapping out per second from t = T - $__rate_interval to t = T",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(rate(node_memory_swapped_out_pages_total[$__rate_interval]) * $blockSize)/(1024 * 1024)",
     "legendFormat": "curr (MB)"
    },
    {
     "expr": "(delta(node_memory_swapped_out_pages_total[$__range]) * $blockSize)/(1024 * 1024)",
     "legendFormat": "total (MB)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IO (per second)",
   "type": "timeseries",
   "description": "A datapoint at time t = T represents avg amount of IO per second from t = T - $__rate_interval to t = T",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"disk0\"}[$__rate_interval]) / (1024 * 1024)",
     "legendFormat": "read (MB)"
    },
    {
     "expr": "delta(node_disk_read_bytes_total{device=\"disk0\"}[$__range]) / (1024 * 1024)",
     "legendFormat": "read total (MB)"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"disk0\"}[$__rate_interval]) / (1024 * 1024)",
     "legendFormat": "write (MB)"
    },
    {
     "expr": "delta(node_disk_written_bytes_total{device=\"disk0\"}[$__range]) / (1024 * 1024)",
     "legendFormat": "write total (MB)"
    }
   ]
  },
  {
   "title": "Requests (per second)",
   "type": "timeseries",
   "description": "A datapoint at time t = T represents avg number of requests per second from t = T - $__rate_interval to t = T",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"disk0\"}[$__rate_interval])",
     "legendFormat": "read (count)"
    },
    {
     "expr": "delta(node_disk_reads_completed_total{device=\"disk0\"}[$__range])",
     "legendFormat": "total read (count)"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"disk0\"}[$__rate_interval])",
     "legendFormat": "write (count)"
    },
    {
     "expr": "delta(node_disk_writes_completed_total{device=\"disk0\"}[$__range])",
     "legendFormat": "total write (count)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic - $network_interfaces (per second)",
   "type": "timeseries",
   "description": "A datapoint at time t = T represents avg amount of traffic per second from t = T - $__rate_interval to t = T",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "repeat": "network_interfaces",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$network_interfaces\"}[$__rate_interval])/(1024 * 1024)",
     "legendFormat": "received (MB)"
    },
    {
     "expr": "delta(node_network_receive_bytes_total{device=~\"$network_interfaces\"}[$__range])/(1024 * 1024)",
     "legendFormat": "received total (MB)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$network_interfaces\"}[$__rate_interval])/(1024 * 1024)",
     "legendFormat": "sent (MB)"
    },
    {
     "expr": "delta(node_network_transmit_bytes_total{device=~\"$network_interfaces\"}[$__range])/(1024 * 1024)",
     "legendFormat": "sent total (MB)"
    }
   ]
  }
 ]
}